import type { Metadata } from "next";
import Header from "@/components/header";
import Main from "@/components/main";
import Footer from "@/components/footer";
import '@/styles/global.scss';

export const metadata: Metadata = {
  title: "Create Next App | Lenny Peters",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Main>
          {children}
        </Main>
        <Footer/>
      </body>
    </html>
  );
}
